### ISSUE TITLE
Checking getting stuck

### ISSUE THREAD

**Issue by ondrej-fabry** [tcort/markdown-link-check#59]
The program appears to get stuck with latest version v3.7.0.

It seems it occurred in your travis as well: https://travis-ci.org/tcort/markdown-link-check/jobs/408319948

We have to use version v3.6.2 for now.

**Comment by tcort** [comment]
Should be fixed by #58 which was published in v3.7.1
https://travis-ci.org/tcort/markdown-link-check/builds/408421707

**Comment by ondrej-fabry** [comment]
This is definitely not fixed. We are still experiencing issues with latest version.. https://travis-ci.org/ligato/vpp-agent/builds/409076311?utm_source=github_status&utm_medium=notification
