### ISSUE TITLE
No result and "possible EventEmitter memory leak detected" with lots of files

### ISSUE THREAD

**Issue by hugovk** [tcort/markdown-link-check#9]
Node v4.1.2

It's working with a single file:
```bash
$ markdown-link-check ./README.md
```
https://travis-ci.org/hugovk/botwiki.org#L599

And on five files:
```bash
$ cat *.md | markdown-link-check
```
https://travis-ci.org/hugovk/botwiki.org#L635

But not on 635 files combined, where the command eventually times out:
```bash
$ find content/ -name '*.md' -exec cat {} \; > /tmp/all-the-markdown.md
The command "find content/ -name '*.md' -exec cat {} \; > /tmp/all-the-markdown.md" exited with 0.

$ markdown-link-check /tmp/all-the-markdown.md
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```
https://travis-ci.org/hugovk/botwiki.org#L686

**Comment by tcort** [comment]
I did some testing and it looks like it was checking **all** of the links in parallel which lead to unexpected results when there are a large number of links. I've limited the number of parallel requests, so that should fix this problem. If not, let me know. I was able to successfully test a markdown text with 10,000 links in it. The new version is `2.0.1`

**Comment by hugovk** [comment]
Thanks, I now get the link checking, but the possible memory leak is still shown:
https://travis-ci.org/hugovk/botwiki.org#L690

```bash
195.77s$ markdown-link-check /tmp/all-the-markdown.md
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:239:17)
    at Request.init (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:495:8)
    at Redirect.onResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/lib/redirect.js:148:11)
    at Request.onRequestResponse (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/markdown-link-check/node_modules/request/request.js:885:22)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
[✖] /about/team/
[✓] mailto:stefan@botwiki.org
[✖] #articles
[✓] http://www.dailydot.com/technology/microsoft-bots-smarterchild-future/
[✓] http://dailydot.com/
[✓] http://www.andfestival.org.uk/events/botwiki-monthly-bot-challenge/
[✖] http://andfestival.org/
[✓] http://www.laboiteverte.fr/monde-fantastique-tweetbots/
[✓] http://www.laboiteverte.fr/
[✓] http://technical.ly/brooklyn/2016/03/02/find-any-bot-ever-with-this-online-bot-encyclopedia/
[✓] http://technical.ly/
[✓] http://hyperallergic.com/280055/a-wiki-for-all-the-internets-bots/
[✓] http://hyperallergic.com/
[✓] https://github.com/botwiki/
[✓] https://botmakers.org/
[✓] https://github.com/botwiki/botmakers.org/blob/master/Code%20of%20Conduct.md
[✓] https://botwiki.org/tag/interview/
[✓] https://botwiki.org/monthly-bot-challenge/
[✓] https://www.patreon.com/botwiki
[✓] https://gratipay.com/botwiki-org/
[✓] https://www.paypal.me/stefanbohacek
[✖] bitcoin:18WDyJFShLcLVCRyiEm3MijbCsBjcxG4mH?amount=0.025&amp;label=Botwiki
[✓] https://www.digitalocean.com/
[✓] https://www.digitalocean.com/?refcode=9e279abc3337
[✖] /merch/
[✓] https://twitter.com/intent/tweet?source=https://botwiki.org/about/support&amp;text=Support%20Botwiki,%20Botmakers.org,%20and%20the%20Bot!%20zine%20newsletter%20https://botwiki.org/about/support&amp;via=botwikidotorg
[✖] /about/team#stefan
[✓] http://www.oldbookillustrations.com/
[✓] http://emojione.com/
[✓] http://www.aha-soft.com/free-icons/
[✓] https://creativemarket.com/chiotis
[✓] http://www.freepik.com
[✓] https://twitter.com/davegandy
[✓] http://www.flaticon.com
[✓] http://creativecommons.org/licenses/by/3.0/
[✖] /about/team#veronica
[✓] https://botzine.org/
[✖] /projects
[✓] https://twitter.com/botwikidotorg
[✖] mailto:stefan@botwiki.org?cc=v@veronicabelmont.com
[✓] https://twitter.com/FortheRecordBot
[✓] https://twitter.com/HelCityNews
[✓] https://twitter.com/hugovk
[✓] https://twitter.com/11_11_bot
[✓] https://twitter.com/swayandsea
[✓] http://www.twitter.com/particlemanbot
[✓] http://cheapbotsdonequick.com/source/particlemanbot
[✓] https://twitter.com/twerribletweets
[✓] https://en.wikipedia.org/wiki/Particle_Man
[✓] https://en.wikipedia.org/wiki/They_Might_Be_Giants
[✓] http://twitter.com/lovetheseas
[✓] https://twitter.com/lovetheseas
[✓] https://twitter.com/sixworderbot
[✓] https://github.com/hugovk/randomsentencebot
[✓] http://twitter.com/pngbot
[✓] https://twitter.com/pngbot
[✓] https://github.com/vgan/pngbot
[✓] https://twitter.com/vgan
[✓] http://twitter.com/pls_take_breaks
[✓] https://twitter.com/pls_take_breaks
[✓] http://cheapbotsdonequick.com/
[✓] http://twitter.com/tauntbot
[✓] https://twitter.com/tauntbot
[✓] https://twitter.com/breefy
[✓] https://en.wikipedia.org/wiki/Monty_Python
[✓] http://fusion.net/story/208920/tauntbot-twitter-bot-insults-you/
[✓] http://twitter.com/congressedits
[✓] https://twitter.com/congressedits
[✓] https://twitter.com/edsu
[✓] https://github.com/edsu/anon
[✓] http://twitter.com/theroboreporter
[✓] https://twitter.com/theroboreporter
[✓] https://twitter.com/tomroyal
[✓] http://www.tomroyal.com/blog/2015/01/18/the-robot-reporter/
[✓] https://twitter.com/PotterPapers
[✓] https://github.com/hugovk/cheapbotsdonequick
[✓] https://en.wikipedia.org/wiki/Harry_Potter
[✓] https://twitter.com/zarabotza/
[✓] https://en.wikipedia.org/wiki/Zaragoza
[✓] https://twitter.com/nixibot
[✓] https://github.com/hugovk/word-tools
[✓] https://twitter.com/eksennowplaying
[✓] https://twitter.com/ahmetkun
[✓] http://www.radioeksen.com/
[✓] https://en.wikipedia.org/wiki/Istanbul
[✓] https://www.youtube.com/
[✓] http://twitter.com/godtributes
[✓] https://twitter.com/godtributes
[✓] https://github.com/jimkang/godtributes
[✓] https://twitter.com/deathmtn
[✓] http://twitter.com/tinydnd
[✓] https://twitter.com/tinydnd
[✓] https://twitter.com/doeg
[✓] http://twitter.com/pomological
[✓] https://twitter.com/pomological
[✓] https://twitter.com/xor
[✓] http://www.usda.gov/wps/portal/usda/usdahome
[✓] http://usdawatercolors.nal.usda.gov/pom/home.xhtml
[✓] https://twitter.com/__birds__
[✓] http://cheapbotsdonequick.com/source/__birds__
[✓] https://twitter.com/RobertVinluan
[✓] http://twitter.com/censusAmericans
[✓] https://twitter.com/censusAmericans
[✓] http://fivethirtyeight.com/datalab/introducing-censusamericans-a-twitter-bot-for-america/
[✓] https://twitter.com/BostonSnowbot
[✓] https://github.com/molly/boston-snowbot
[✓] https://twitter.com/molly0x57
[✓] http://forecast.io/
[✓] http://twitter.com/one_algorithm
[✓] https://twitter.com/one_algorithm
[✓] https://twitter.com/nickmofo
[✓] https://twitter.com/BrutalistEngine
[✓] https://twitter.com/nicolastilly
[✓] http://twitter.com/TatsIllustrated
[✓] https://twitter.com/TatsIllustrated
[✓] https://twitter.com/BooDooPERSON
[✓] https://twitter.com/knuckle_tat
[✓] http://twitter.com/menubot
[✓] https://twitter.com/menubot
[✓] https://github.com/hugovk/menubot
[✓] http://menubot.tumblr.com/
[✓] http://www.nypl.org/
[✓] http://menus.nypl.org/
[✓] https://github.com/NYPL/menus-api
[✓] https://twitter.com/alt_text_bot
[✓] https://github.com/ckundo/alt-text-bot
[✖] https://github.com/ckundo/alt-text-bot/blob/master/README.md
[✓] http://cloudsightapi.com/
[✓] http://alttextbot.com
[✓] https://twitter.com/ckundo
[✓] http://twitter.com/itsthisyear
[✓] https://twitter.com/itsthisyear
[✓] http://whatyearisit.robertvinluan.com/2014/
[✓] http://twitter.com/itsYrLuckyDay
[✓] https://twitter.com/itsYrLuckyDay
[✓] https://twitter.com/colewillsea
[✓] https://twitter.com/unicode_garden
[✓] https://twitter.com/v21
[✓] https://twitter.com/ilovethisbot
[✓] https://github.com/sammorrisdesign/i-heart-this-bot
[✓] https://twitter.com/sammorrisdesign
[✓] https://en.wikipedia.org/wiki/I_Love_New_York
[✓] https://twitter.com/Revenantbot
[✓] https://twitter.com/M_PF
[✓] https://twitter.com/iederwoord
[✖] https://www.botwiki.org/bots/bot,twitterbots/everyword/
[✓] https://twitter.com/johnschop
[✓] http://johnschop.nl/2012-08-13/iederwoord-waarom
[✓] http://twitter.com/dronestream
[✓] https://twitter.com/dronestream
[✓] https://twitter.com/joshbegley
[✓] https://en.wikipedia.org/wiki/Unmanned_aerial_vehicle#Military_Uses
[✓] https://twitter.com/AgencyNames
[✓] https://twitter.com/adcrimer
[✓] https://twitter.com/VillanelleBot
[✓] https://twitter.com/avoision
[✓] http://avoision.com/2015/08/26/villanelle-bot-poems-in-the-villanelle-form-created-using-random-posts-from-twitter.php
[✓] http://twitter.com/thesefutures
[✓] https://twitter.com/thesefutures
[✓] https://twitter.com/ranjit
[✓] https://twitter.com/motherboard
[✓] http://motherboard.vice.com/read/twitter-bot-predicts-these-futures
[✓] https://twitter.com/1_thing_idk_why
[✖] https://github.com/coleww/1_thing_idk_why
[✓] https://en.wikipedia.org/wiki/In_the_End
[✓] https://twitter.com/BabellingBorges
[✓] https://twitter.com/mattlaschneider
[✓] https://en.wikipedia.org/wiki/Jorge_Luis_Borges
[✓] https://twitter.com/auto_automata
[✓] https://github.com/nossidge/1d-cellular-automata
[✓] https://twitter.com/nossidge
[✓] http://tilde.town
[✓] https://twitter.com/anagramatron
[✓] https://twitter.com/cmyr
[✓] https://en.wikipedia.org/wiki/Anagram
[✓] http://anagramatron.tumblr.com/
[✓] https://twitter.com/MancOrchSays
[✓] https://github.com/WhiteFangs/TwitterLyricsBot
[✓] https://twitter.com/White_Fangs
[✓] https://en.wikipedia.org/wiki/Manchester_Orchestra
[✖] https://twitter.com/WeatherKnow
[✓] https://twitter.com/vaibhaw_vipul
[✓] https://twitter.com/angryrichpeople
[✓] https://github.com/tpinecone/angry_rich_people
[���] https://twitter.com/spine_cone
[✓] http://www.yelp.com/
[✓] http://twitter.com/SPACEBOT5000
[✓] https://twitter.com/SPACEBOT5000
[✓] https://github.com/swizzard/spacebot5000
[✓] https://twitter.com/swizzard
[✓] https://processing.org/
[✓] https://twitter.com/autocompleterap
[✓] https://github.com/jimkang/autocompleterap
[✓] http://ohhla.com
[✓] https://twitter.com/EveryFinnishNo
[✓] https://github.com/hugovk/everyfinnishno
[✓] http://twitter.com/minuseveryone
[✓] https://twitter.com/minuseveryone
[✓] https://twitter.com/revdancatt
[✓] http://revdancatt.com
[✓] http://tumblr.com/
[✓] http://minuseveryone.tumblr.com/
[✓] http://garfieldminusgarfield.net/
[✓] https://en.wikipedia.org/wiki/Garfield_Minus_Garfield
[✓] https://medium.com/panel-frame/why-minus-everyone-b3278319d8ff
[✓] https://twitter.com/imgshredder
[✓] https://twitter.com/ronallo
[✓] http://ronallo.com/bots/imgshredder/
[✓] https://twitter.com/genderposibot
[✓] https://twitter.com/hologramvron
[✓] http://twitter.com/FinnishFlags
[✓] https://twitter.com/FinnishFlags
[✓] https://github.com/hugovk/whyaretheflagsup
[✓] https://whyaretheflagsup.github.io/
[✓] https://whyaretheflagsup.github.io/?date=1-may-2015
[✓] http://twitter.com/MagicRealismBot
[✓] https://twitter.com/MagicRealismBot
[✓] https://twitter.com/yeldora_
[✓] https://twitter.com/chrisrodley
[✓] https://en.wikipedia.org/wiki/Magic_realism
[✓] https://twitter.com/haikumurakami
[✓] https://twitter.com/SongHia
[✓] https://en.wikipedia.org/wiki/Haruki_Murakami
[✓] http://haikumurakami.tumblr.com/
[✓] http://twitter.com/tiny_star_field
[✓] https://twitter.com/tiny_star_field
[✓] https://twitter.com/katierosepipkin
[✓] https://twitter.com/wayback_exe
[✓] https://github.com/muffinista/wayback_exe
[✓] https://twitter.com/muffinista
[✓] https://archive.org/web/
[✓] http://muffinlabs.com/wayback_exe/
[✓] https://twitter.com/HypernymBot
[✓] https://github.com/Gangles/hypernym-bot
[✓] https://twitter.com/Gangles
[✓] https://en.wikipedia.org/wiki/Hyponymy_and_hypernymy
[✓] https://twitter.com/accidental575
[✓] https://twitter.com/eusonic
[✓] https://en.wikipedia.org/wiki/Haiku
[✓] http://twitter.com/rule110_bot
[✓] https://twitter.com/rule110_bot
[✓] https://github.com/tahnok/rule110
[✓] https://twitter.com/tahnok
[✓] https://en.wikipedia.org/wiki/Rule_110
[✓] https://twitter.com/how2butt
[✓] https://github.com/tpinecone/tweetbots
[✓] http://www.wikihow.com/
[✓m] https://www.twitter.com/bayareabotarts
[✖] https://twitter.com/www.twitter.com/bitpixi
[✓] http://www.meetup.com/Bay-Area-Bot-Arts/
[✓] https://twitter.com/a_quilt_bot
[✓] https://twitter.com/bobpoekert
[✓] http://www.cs.cornell.edu/~dph/papers/seg-ijcv.pdf
[✓] https://twitter.com/snippet_jpg
[✓] http://twitter.com/precure_screens
[✓] https://twitter.com/precure_screens
[✓] https://twitter.com/Kimik00
[✓] https://en.wikipedia.org/wiki/Pretty_Cure
[✓] http://twitter.com/FireworksBot
[✓] https://twitter.com/FireworksBot
[✓] https://twitter.com/EvilKimau
[✓] https://golang.org/
[✓] https://botwiki.org/events/#procjam-2015
[✓] http://exponentialdecay.co.uk/blog/not-quite-perfect-a-lil-automatic-twitter-thingy
[✓] https://github.com/exponential-decay/binary-numbers
[✓] https://twitter.com/beet_keeper
[✓] http://exponentialdecay.co.uk/blog/not-quite-perfect-a-lil-automatic-twitter-thingy/
[✓] http://exponentialdecay.co.uk/blog/2015-a-year-in-binary/
[✓] http://twitter.com/dungeon_junk
[✓] http://twitter.com/notinventedhere
[✓] https://twitter.com/usinjuries
[✓] http://www.cpsc.gov/en/Research--Statistics/NEISS-Injury-Data/
[✓] http://twitter.com/KeplerBot
[✓] https://twitter.com/KeplerBot
[✓] https://twitter.com/GeertHub
[✓] https://twitter.com/NASAKepler
[✓] http://barentsen.github.io/k2flix/
[✓] https://twitter.com/ahouseofdust
[✓] http://www.zachwhalen.net/tag/ssbot/
[✓] https://www.edx.org/course/electronic-literature-davidsonx-d004x
[✓] https://twitter.com/AteneumBot
[✓] https://github.com/hugovk/fngbot
[✓] http://www.ateneum.fi/?lang=en
[✓] http://twitter.com/DeepForger
[✓] https://twitter.com/DeepForger
[✓] https://twitter.com/alexjc
[✓] http://nucl.ai/blog/forgeries-user-guide/
[✓] http://twitter.com/pleading_bot
[✓] https://twitter.com/pleading_bot
[✓] https://twitter.com/Lingering_Llama
[✓] https://twitter.com/arslongvitabrev
[✓] https://twitter.com/White_fangs
[✓] https://es.wikipedia.org/wiki/Haiku
[✓] http://twitter.com/permitbot
[✓] https://twitter.com/permitbot
[✓] https://github.com/chagan/permitbot
[✓] https://data.cityofchicago.org/Buildings/Building-Permits/ydr8-5enu
[✓] https://twitter.com/chrishagan
[✓] http://twitter.com/licensemee
[✓] https://twitter.com/licensemee
[✖] https://twitter.com/http://lifeofaudrey.com/
[✓] http://twitter.com/thesaurusgame
[✓] https://twitter.com/thesaurusgame
[✓] http://thesaurusgame.tumblr.com/
[✓] https://twitter.com/SorryPatMcCrory
[✓] https://twitter.com/PatMcCroryNC
[✓] https://twitter.com/apologytrump
[✓] http://www.charlotteobserver.com/news/politics-government/article68401147.html
[✓] https://medium.com/@samplereality/a-protest-bot-is-a-bot-so-specific-you-cant-mistake-it-for-bullshit-90fe10b7fbaa#.1k6b4hknf
[✓] https://twitter.com/vroom_vroom_bot
[✓] https://twitter.com/xxRobot
[✓] https://twitter.com/NixieBot
[✓] https://github.com/Zedsquared/NixieBot
[✓] https://twitter.com/Zedsquared
[✓] https://twitter.com/hashtag/NixieBotShowMe?src=hash
[✓] https://www.raspberrypi.org
[✓] http://nixiebot.tumblr.com
[✓] http://nixiebot.tumblr.com/ref
[✓] https://twitter.com/tinysubversions
[✓] https://snapchat.com/
[✓] https://en.wikipedia.org/wiki/Snapchat
[✖] /bots/snapchat-bots/hypem
[✖] http://hypem.com/
[✓] https://twitter.com/hypem
[✓] https://twitter.com/fascinated
[✓] http://blog.hypem.com/2015/05/hype-machine-on-snapchat/
[✓] https://twitter.com/fascinated/status/653710201598681088
[✓] http://m.me/CalcBot
[✖] https://twitter.com/http://www.gifhip.com
[✓] https://m.me/memegenBot
[✓] https://twitter.com/3x14159265
[✓] https://pennycat.co
[✓] https://twitter.com/levkangin
[✓] http://m.me/soccerfanbot
[✓] https://twitter.com/Momoh_RR
[✓] http://www.jobbot.me
[✓] https://twitter.com/andre_z
[✓] https://m.me/Publico
[✓] https://twitter.com/PauloQuerido
[���] http://www.fitmeal.com/
[✓] https://twitter.com/gduverger
[✓] http://m.me/ThePokedexBot
[✓] https://twitter.com/RizkSaade
[✓] https://www.producthunt.com/tech/pokedex-bot
[✓] https://www.facebook.com/ThePokedexBot/
[✓] https://m.me/epytom
[✖] https://www.linkedin.com/in/anastasia-sartan-67a4583a
[✓] https://youtu.be/NEdDHLzZtIE
[✓] https://epytom.com/start/
[✓] https://chatbotsmagazine.com/choosing-not-to-choose-34115855e2f3#.an2jq7qsd
[✓] https://www.instagram.com/epytom/
[✓] https://hipstercatbot.com
[✓] https://twitter.com/electrobabe
[✓] https://www.facebook.com/claire30secondstofly/
[✓] https://twitter.com/Felicia_S_
[✓] https://twitter.com/rikyvittoria
[✓] http://m.me/36LoveQuestions
[✓] https://www.facebook.com/botprint
[✖] https://twitter.com/poriruaapps
[✓] https://en.wikipedia.org/wiki/Walgreens
[✓] https://m.me/rentiez
[✓] https://twitter.com/Rentiezz
[✓] https://www.producthunt.com/tech/billhero-messenger-bot
[✓] https://twitter.com/billhero
[✓] https://www.messenger.com/
[✓] https://www.facebook.com/
[✖] /tag/facebook+bot
[✓] https://docs.google.com/spreadsheets/d/1t2L4CjHgjtvtz2xXJnFJ1TCwy1H0dAVLeSVvv0y6GGs/edit?usp=sharing
[✖] /tutorials/facebook-messenger-bots
[✖] /bots
[✓] http://m.me/mealoubot
[✓] https://twitter.com/doriancamilleri
[✓] http://www.mealou.co
[✓] http://m.me/NearMinderBot
[✓] https://twitter.com/NearMinderBot
[✓] http://m.me/jobpal
[✓] https://twitter.com/lucdudler
[✓] http://digiday.com/brands/new-facebook-chatbot-help-find-next-job/
[✓] http://www.snapmunk.com/6-solid-chatbots-check/
[✓] http://www.eleconomista.es/negocio-digital/innovacion/noticias/7611029/06/16/Un-nuevo-chatbot-de-Facebook-Messenger-ayudara-en-la-busqueda-de-empleo.html
[✓] http://telegram.me/MetricsBot
[✓] http://telegram.me/alukyanov
[✓] https://telegram.me/AlterraBot
[✓] http://m.me/alterra.cc
[✓] https://twitter.com/bilb02
[✓] https://telegram.me/BlackJackBot
[✓] https://telegram.me/d_Rickyy_b
[✓] https://en.wikipedia.org/wiki/Blackjack
[✖] https://telegramlogin.com
[✓] https://github.com/3x14159265/telegramlogin
[✓] http://telegram.me/sneakerbits_bot
[✓] https://twitter.com/pmcpinto
[✓] https://telegram.me/qwasapbot
[✓] https://twitter.com/sofocles
[✓] https://qwasap.com
[✓] https://reddit.com/
[✖] https://en.wikipedia.org/wiki/Telegram_(software
[✖] /tag/telegrambot
[✖] /tutorials/telegram-bots
[✖] /resources/telegram-bots
[✓] https://docs.google.com/spreadsheets/d/1uQP3f2bWuPapTn_1FUcL67jW9MwLzSjysji39pmyUxY/edit#gid=2104461983
[✓] https://storebot.me/
[✓] http://botfamily.com/
[✖] /what-is-a-bot
[✓] https://en.wikipedia.org/wiki/Internet_bot
[✓] http://peek.usertesting.com/result/20922996954524
[✖] /articles/#general-essays
[✓] https://www.tumblr.com/
[✓] https://twitter.com/
[✓] http://damnyoubatman.com/
[✓] http://hungernames.com/
[✖] #browse-bots-by-category
[✖] #browse-bots-by-network
[✖] /tutorials/
[✖] /articles/
[✓] https://twitter.com/fourtonfish
[✓] https://botwiki.org/submit-your-bot
[✖] /tag/bot+poetry
[✖] /tag/bot+images
[✖] /tag/bot+gif
[✖] /tag/bot+emoji
[✖] /tag/bot+game
[✖] /tag/bot+generative/
[✖] /tag/bot+non-english
[✖] /bots/iot
[✖] /tag/bot+opensource
[✖] /tag/bot+monthlybotchallenge+winner
[✖] /bots/twitterbots/
[✖] /bots/slackbots/
[✖] /bots/tumblr-bots/
[✖] /bots/facebook-messenger-bots/
[✖] /bots/youtube-bots/
[✖] /bots/redditbots/
[✖] /bots/telegram-bots/
[✖] /tag/snapchatbot/
[✖] /tag/kikbot/
[✖] /bots/trello-bots/
[✖] /random-bot
[✖] #bot-directories
[✓] https://botlist.co/
[✓] https://www.botpages.com/
[✓] https://www.chatbots.org/
[✓] https://botwiki.org/survey/quick-bot-survey
[✓] https://rmendes.net
[✓] https://twitter.com/Almar
[✓] https://twitter.com/lizmrush
[✓] https://www.kirsle.net
[✓] https://github.com/swizzard
[✓] http://enki2.tumblr.com
[✓] http://chatbotfriends.altervista.org/
[✓] https://github.com/cryptobird
[✓] https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol
[✓] https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol
[✓] https://en.wikipedia.org/wiki/Network_News_Transfer_Protocol
[✓] https://twitter.com/air_hadoken
[✓] http://v21.io/games.html
[✓] http://v21.io/talks.html
[✓] http://v21.io/blog/
[✖] /tag/botmaker
[✓] http://playfabulousbeasts.com/
[✓] http://v21.io/cubes/
[✓] http://hellisotherpeople.co.uk/
[✖] /bots/twitterbots/unicode_garden
[✓] http://www.blog.radiator.debacle.us/2015/10/not-manifesto.html
[✓] http://dkmfxr0axh7rumhs3ppv.tumblr.com/
[✓] https://botwiki.org/bots/twitterbots/pngbot
[✓] http://v21.io/punchthecustard
[✖] /content/interviews/images/past-rage-comic-full.jpg
[✓] http://v21.io/blog/rules/
[✓] https://twitter.com/galaxykate
[✓] https://github.com/galaxykate/tracery
[✓] http://feral-vector.com/
[✓] https://en.wikipedia.org/wiki/OAuth
[✓] http://v21.io/iwilldancetheoauthdanceforyou/
[✓] https://twitter.com/cant_miss_it
[✓] https://github.com/v21/tracerybot/
[✖] /tutorials/botmaking-with-openshift/
[✓] https://rundexter.com/
[✓] https://twitter.com/nyxtaki
[✓] https://twitter.com/miniaturemazes
[✓] http://v21.io/blog/tools-for-novices/
[✓] https://en.wikipedia.org/wiki/Dick_Dastardly
[✓] https://twitter.com/metaphormagnet
[✓] https://botwiki.org/
[✖] /content/interviews/images/nick-photo.png
[✓] https://slack.com/
[✓] https://botwiki.org/articles/
[✓] https://addons.mozilla.org/en-us/firefox/addon/greasemonkey/
[✓] https://xkcd.com/json.html
[✖] /content/interviews/images/ash.png
[✓] https://twitter.com/Ash_Hathaway/
[✓] http://www.ibm.com/smarterplanet/us/en/ibmwatson/
[✓] http://www.technologyreview.com/view/545316/ai-algorithm-identifies-humorous-pictures/
[✓] https://algorithmia.com/
[✓] https://beepboophq.com/
[✖] /content/interviews/images/erin-photo.jpg
[✓] https://twitter.com/emckean
[✓] https://en.wikipedia.org/wiki/Wordnik
[✓] http://developer.wordnik.com
[✖] /tag/wordnik+active
[✓] https://wordnik.com/adoptaword
[✓] https://wordnik.com
[✓] https://twitter.com/infixbot
[✓] https://twitter.com/BotrahamLincoln
[✓] http://developer.wordnik.com/
[✓] https://en.wikipedia.org/wiki/Yahoo!_Pipes
[✖] /bots/twitterbots/TwoHeadlines
[✓] http://dressaday.com/
[2m✓] http://semicolonappreciationsociety.com/
[✓] https://twitter.com/emckean/
[✓] http://www.abc.net.au/science/articles/2014/08/12/4065062.htm
[✓] http://www.onlymelbourne.com.au/statue-charles-la-trobe
[✓] http://www.ted.com/talks/erin_mckean_redefines_the_dictionary
[✓] http://blog.ted.com/erin_mckean_lau/
[✓] http://2015.xoxofest.com/
[✖] /events/#nyc-botally-meetup
[✓] http://www.meetup.com/Bay-Area-Wordnik-Meetup/
[✓] http://fortune.com/2014/05/13/10-questions-erin-mckean-founder-reverb/
[✓] http://botzine.org/
[✖] /tag/interview
[✖] #introduction
[✓] https://botmakers.slack.com/messages/announcements/
[✓] https://github.com/botwiki/botmakers.org/commits/master/Code%20of%20Conduct.md
[✓] https://botmakers.slack.com/messages/code-of-conduct/
[✓] https://botmakers.slack.com/messages/@stefan/details/
[✖] #code-of-conduct
[✖] #what-is-considered-harassment
[✓] https://docs.google.com/document/d/1bka4o1RE9RPUeoUzgpTIKRWsgWHzZEKEADialnv7haQ/edit?pli=1
[✓] https://twitter.com/search?f=tweets&amp;q=%23botIDEA
[✖] http://www.racialicious.com/2012/05/02/a-historical-guide-to-hipster-racism/
[✖] #language-and-communication
[✓] https://subfictional.com/2012/07/02/language-matters-stop-using-guys-to-address-mix-gender-groups/
[✓] http://www.huffingtonpost.com/rachel-cohenrottenberg/doing-social-justice-thou_b_5476271.html
[✓] https://en.wikipedia.org/wiki/List_of_disability-related_terms_with_negative_connotations
[✓] http://isthisableism.tumblr.com/sluralternatives
[✓] http://whatever.scalzi.com/2012/05/15/straight-white-male-the-lowest-difficulty-setting-there-is/
[✖] #on-using-slack
[✓] https://slack.com/is
[✓] https://slack.zendesk.com/hc/en-us/articles/201259356-Using-slash-commands
[✖] #am-i-posting-in-the-right-channel
[✓] https://botmakers.slack.com/messages/general/details/
[✖] #can-i-test-my-bot-here
[✓] https://github.com/botwiki/botmakers.org/blob/master/BOTS.md
[✖] #notes
[✓] https://adainitiative.org/2014/02/howto-design-a-code-of-conduct-for-your-community/
[✓] https://www.djangoproject.com/conduct/
[✓] http://lgbtq.technology/coc.html
[✖] #theme
[✓] http://www.vogue.com/13403807/mulder-hot-take-the-x-files-twitter-bot/
[✓] http://algopop.tumblr.com/post/131697941088/allmybots-the-friends-botnet-re-creates
[✓] https://twitter.com/marvelplots
[✓] https://twitter.com/tvcommentbot
[✓] https://twitter.com/CSPANFive
[✓] http://algopop.tumblr.com/post/124318458893/word-wars-julien-deswaef-word-wars-a-new
[✖] /tag/film%20and%20tv
[✖] #prize
[✓] http://www.andfestival.org.uk/
[✖] /events/andfestival-art-of-bots
[✖] #winner
[✓] http://cosmophagy.tumblr.com
[✖] /bots/twitterbots/BMovieGenerator/
[✖] /monthly-bot-challenge/
[✖] /bots/twitterbots/donorschamps
[✓] https://twitter.com/gundeaths
[✓] https://opennews.org/
[✓] https://source.opennews.org
[✓] https://source.opennews.org/en-US/articles/tags/botweek/
[✖] /bots/twitterbots/ItIsYourData/
[✓] https://www.google.com/search?q=local+time+est
[✖] /tag/opensource
[✖] /botmaker-badges/#monthly-bot-challenge-badge
[✖] #prizes
[✓] http://botmakers.org/code-of-conduct/
[✓] https://support.twitter.com/articles/76915#replies-mentions
[✖] /about/supporters/
[✓] https://twitter.com/deer_ful
[✓] https://botwiki.org/bots/twitterbots/thetinygallery/
[✓] https://twitter.com/nypl_labs
[✓] https://twitter.com/nypl
[✓] http://digitalcollections.nypl.org/
[✓] http://api.repo.nypl.org/
[✓] http://github.com/nypl-publicdomain/
[✓] http://publicdomain.nypl.org/
[✓] https://twitter.com/nypl_labs/lists/nypl-bot-family/members
[✓] https://en.wikipedia.org/wiki/Public_domain
[✓] https://archive.org/details/feature_films
[✓] http://digitalcomicmuseum.com/
[✓] https://www.flickr.com/groups/publicdomain/
[✖] /bots/twitterbots/snippet_jpg/
[✖] /bots/
[✓] https://botwiki.org/tutorials/
[✖] #past-sponsors
[✖] #page-content
[✖] #misbehaving-bots
[✖39m] #biased-algorithms
[✖] #dangers-in-automation
[✖] #general-resources
[✖] #see-also
[✓] https://fourtonfish.com/blog/2016-03-18-you-are-the-bot/
[✖] bots-should-punch-up
[✖] /articles/basic-twitter-bot-etiquette-tiny-subversions
[✓] http://www.wired.com/2016/04/bots-emergent-behavior-deception/
[✓] http://motherboard.vice.com/read/how-to-make-a-not-racist-bot
[✓] http://smerity.com/articles/2016/tayandyou.html
[✓] https://www.washingtonpost.com/news/the-intersect/wp/2016/03/25/not-just-tay-a-recent-history-of-the-internets-racist-bots/
[✓] http://www.slate.com/blogs/future_tense/2015/02/25/who_is_responsible_for_death_threats_from_a_twitter_bot.html
[✓] https://www.linkedin.com/pulse/so-your-ai-bot-went-haywire-should-you-care-azeem-azhar?trk=v-feed
[✓] https://blog.howdy.ai/what-good-is-a-bad-bot-841226281a0e#.1ef1zinl9
[✓] https://medium.com/slack-developer-blog/the-bot-rulebook-a442d9fb21cb#.cd051jijs
[✓] https://blog.howdy.ai/where-many-bots-will-fail-68ae163e2473#.2gtskxus8
[✓] http://t.wjt.me.uk/post/151462998480/three-years-of-fewerror
[✓] https://www.propublica.org/series/machine-bias
[✖] http://www.nytimes.com/2016/06/26/opinion/sunday/artificial-intelligences-white-guy-problem.html?_r=0
[✓] http://thenextweb.com/artificial-intelligence/2016/09/30/artificial-intelligence-is-quickly-becoming-as-biased-as-we-are/
[✓] https://freedom-to-tinker.com/blog/randomwalker/language-necessarily-contains-human-biases-and-so-will-machines-trained-on-language-corpora/
[✓] http://deliprao.com/archives/129
[✓] http://mrmrs.io/writing/2016/03/23/the-veil-of-ignorance/
[✓] http://nytlabs.com/blog/2016/03/24/mechanomorphism/
[✓] https://psmag.com/artificial-intelligence-will-be-as-biased-and-prejudiced-as-its-human-creators-38fe415f86dd#.u067yviv3
[✓] http://motherboard.vice.com/read/why-an-ai-judged-beauty-contest-picked-nearly-all-white-winners
[✓] https://www.inverse.com/article/21316-a-i-doesn-t-get-black-twitter-yet
[✓] http://idlewords.com/talks/deep_fried_data.htm
[✖] http://www.nytimes.com/2016/05/19/opinion/the-real-bias-built-in-at-facebook.html?_r=0
[✓] https://source.opennews.org/en-US/articles/designing-news-apps-humanity/
[✓] https://techcrunch.com/2016/09/16/hard-questions-about-bot-ethics/
[✓] https://twitter.com/ashevat
[✓] https://www.theguardian.com/technology/2016/sep/18/official-guidance-robot-ethics-british-standards-institute
[✖] http://www.nytimes.com/2016/09/02/technology/artificial-intelligence-ethics.html
[✓] http://www.inc.com/tess-townsend/jerry-kaplan-artificial-intelligence-new-book.html
[✓] http://ethicalmachines.com/
[✓] https://medium.com/@samim/ethicalmachines-b7c63aaceda5#.zc7yorhn3
[✓] http://moralmachine.mit.edu/
[✓] http://socialmediacollective.org/reading-lists/critical-algorithm-studies/
[✓] https://medium.com/humane-tech
[✓] https://twitter.com/anildash
[✓] https://twitter.com/algorithm_club
[✖] /resources/libraries-frameworks/#language
The command "markdown-link-check /tmp/all-the-markdown.md" exited with 0.
```

**Comment by tcort** [comment]
The EventEmitter warning was caused by a lot of redirects. I've limited the number of redirects to 8 and the warning went away. I've released version `2.0.2` with the change.

**Comment by hugovk** [comment]
Thank you, it's working now! (Took 312 seconds, but then there are over 600 links to check.)

https://travis-ci.org/hugovk/botwiki.org/builds/166671637#L691
